[move-to-yul] Add a struct type to receive the result of external call + bug fix
diem/move pull request #202
Opened 2022-04-08 05:18 UTC by rahxephon89

## Motivation

1. As stated [here](https://docs.soliditylang.org/en/v0.8.13/control-structures.html?highlight=try#try-catch),  Solidity supports different kinds of catch blocks depending on the type of error (Error(string memory reason), Panic(uint errorCode), and bytes memory lowLevelData). To describe the behavior of try/catch statements, a struct type ExternalResult is proposed: 
```
    struct ExternalResult<T> has copy, drop, store {
        value: Option<T>,
        err_vec: Option<vector<u8>>,
        err_str: Option<vector<u8>>,
        panic_code: Option<U256>
    }
```

2. Fix a bug of the method Vector::pop_back for a vector that stores a non-value type in memory.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

TestExternalResult.move

## Related PRs

https://github.com/diem/move/pull/140

2022-04-08 18:48 UTC, junkil-park requested changes
This is great! Once external calls can return `ExternalResult`, I believe that we can make all remaining ERC1155 tests pass.

2022-04-08 18:48 UTC, junkil-park commented on language/evm/stdlib/sources/ExternalResult.move
> +        err_vec: Option<vector<u8>>,
One suggestion. Could we name this as `err_data`, and comment that it represent the low level (raw) data?

2022-04-08 18:48 UTC, junkil-park commented on language/evm/stdlib/sources/ExternalResult.move
> +        err_str: Option<vector<u8>>,
and this one as `err_reason` because it is an error with a reason string?

2022-04-08 18:48 UTC, junkil-park commented on language/evm/stdlib/sources/ExternalResult.move
> +    public fun panic_code<T>(panic_code: U256): ExternalResult<T> {
this one as `public fun panic<T>(code: U256)`?

2022-04-08 18:48 UTC, junkil-park commented on language/evm/stdlib/sources/ExternalResult.move
> +    public fun is_panic_code<T>(result: &ExternalResult<T>): bool {
and this one as `is_panic`?

2022-04-08 23:14 UTC, wrwg submitted a review, later dismissed

2022-04-11 16:06 UTC, junkil-park commented on language/evm/stdlib/sources/ExternalResult.move
> +    public fun unwrap_value<T>(result: ExternalResult<T>): T {
Another minor comment. "unwrap_value " --> "unwrap"?, just to match to the names of Rust's Result API.

2022-04-11 16:06 UTC, junkil-park commented on language/evm/stdlib/sources/ExternalResult.move
> +    public fun unwrap_panic_code<T>(result: ExternalResult<T>): U256 {
`unwrap_panic_code` --> `unwrap_panic`?

2022-11-13 07:33 UTC, closed without merging